### ISSUE TITLE
Randomize Mantras and Dissonance

### ISSUE THREAD

**Issue by jet082** [Coookie93/LaMulana2Randomizer#10]
It would be nice to add mantra scans into the item pool.

Additionally, to add variety to the game (and to reduce the enormous amount of 'required items') it would be nice to have dissonance locations randomized (and to obviously get an item in place of dissonance when you get it). This would have the side-benefits of making the randomizer potentially shorter and adding risky checks (nibiru) that could make races more exciting.

**Comment by Coookie93** [comment]
So i'm currently working on adding the mantras scans to the item pool, the idea of randomising dissonance definitely seems interesting i'll try too look at some point in the future.
