### ISSUE TITLE
Frey Ship

### ISSUE THREAD

**Issue by ratphink** [Coookie93/LaMulana2Randomizer#14]
Was never able to proc the dialgue necessary for Eitri and Bokkr to enable me to grab the Frey's Ship item. Luckily, that item and the Anchor were not manadatory items to grab, just thought I'd point it out that it seems if Freya moves to Frey's location you can't seem to enable this item and potential locks out 2 items in the run.

**Comment by Coookie93** [comment]
Sorry it has been so long since you opened the issue, just want to make sure you scanned the tablet next to the Annwfn Ankh spot, can you possibly remember what dialogue options they were stuck in thanks.
