### ISSUE TITLE
Logic Softlock - Jormungand

### ISSUE THREAD

**Issue by doicm** [Coookie93/LaMulana2Randomizer#15]
I beat all the bosses except jormungand. I triggered the end and beat heimdall. When I went to talk to dude that unlocks jormungand's ankh, I couldn't get him to do it because lemeza and pop were there. I tried going in and out, but couldn't get him to reappear. I can't go through the final door to the spiral boat because I haven't defeated 9 guardians.

In any case, I guess that's a logic bug?

**Comment by Coookie93** [comment]
Fixed in 1.4.1
