### ISSUE TITLE
Logic Softlock - Anchor in Hall of Malice Map Chest

### ISSUE THREAD

**Issue by Starf4ll** [Coookie93/LaMulana2Randomizer#16]
Playing Seed: -450391208, the logic appears to have generated in a way that can not be completed. According to the spoiler log the Anchor is located in the Hall of Malice Map Chest, yet to reach this chest you would have to go through Heaven's Labyrinth, which requires the Anchor to get to from Icefire Treetop.

Being unable to reach HL and subsequently HoM means being unable to defeat all of the Guardians and therefore the seed can't be completed. I'm not sure if there is be a glitch that would allow me to reach HL without the Anchor or if there's some entrance I'm not aware of that isn't on the wiki but progression seems to be stuck based on this item placement.

Seed was generated with the following settings:
- Hand Scanner Randomized
- Codices Randomized
- Mantras Only at murals
- Shops at least one item
- Autoscan Holy Tablets

[spoilers.txt](https://github.com/Coookie93/LaMulana2Randomizer/files/4252520/spoilers.txt)

Edit: So I realized that the logic is probably expecting me to enter HoM from the Corridor of Blood and enter the map room (C-1) from the grail tablet room (C-2) however there is no ladder going up to C-1. I know there's supposed to be a ladder going up but since it's not there I'm thinking maybe it's tied to a trigger that got changed in a patch at some point.

**Comment by reruns** [comment]
I got stuck the same way a few days ago. The trick is that you have the effect of Anchor while wearing Claydoll Suit. It's just not something that comes up outside of pretty much this exact situation. 

Also, yeah, there is no back door into HL. That ladder in HoM has to be activated from the other side.

**Comment by Coookie93** [comment]
Yeah wearing the Claydoll Suit for stuff where the Anchor is needed is in logic, i am planning to add a wiki page explaining some of the less known things. Also yeah Hall of Malice got changed so you have to enter from Heavens Labyrinth to activate the ladder now.

**Comment by Starf4ll** [comment]
Oh dang I never even though of that, that makes so much more sense. I did feel like I had to be missing something since it seemed like such an obvious thing that the logic should account for, guess I didn't think about it hard enough. Oh well.
