### ISSUE TITLE
Self-Locked Mantra

### ISSUE THREAD

**Issue by JetBox** [Coookie93/LaMulana2Randomizer#18]
I was recently playing a randomizer with default settings except that Mantras are randomized "Only at murals". Over the course of the game, I was able to unlock every Mantra except for Wind. Which means I wouldn't have access to the Twins Chest, the Buried Fortress, and the Child Mural in the Echidna Worshiping room (the one connected from Surface). This means the Wind Mantra is locked behind this mural, but I need the Wind Mantra to reveal the mural. So I can't fight the 9th Child. I'm not too upset because I was able to complete the game entirely except for this (am able to enter Spiral Hell), but I thought it would be worth reporting.

Details------------------
Seed: 877440795
Options: Default except Mantras are randomized "Only at murals"
Other: Auto-place Crystal Skulls and Auto-scan Holy Tablets

**Comment by Coookie93** [comment]
I apologise for the late reply, it seems that Wind was placed at the Beo-Eglana Mural which is fine for these settings.
