### ISSUE TITLE
Confused on Future Development Company rules in Logic.

### ISSUE THREAD

**Issue by lonegraywolf2000** [Coookie93/LaMulana2Randomizer#23]
Within the current logic file, there are two places that explicitly mention Future Development Company as a requirement. The randomizer has an option for not requiring that software for warping to particular areas. Shouldn't that rule also affect Eternal Prison Doom -> Eternal Prison Doom Top and the Death Sigil Chest in Eternal Prison Gloom?

I'm just wondering if something like `Setting(FDC for Backside)` should be added to keep it in check.

**Comment by Coookie93** [comment]
The setting to require FDC in logic for accessing backside fields is there so that you don't have to keep walking back to the field which can be real tedious. For the places its actually required in logic it is because it allows for more possibilities for that check to be in logic.
