### ISSUE TITLE
Cannot pick up randomized dissonance/progressive items in vanilla dissonance locations (softlock)

### ISSUE THREAD

**Issue by SoulSoldier64** [Coookie93/LaMulana2Randomizer#26]
First of all, great job with the rando it's pretty good!

Second of all, I've encountered an issue when randomizing dissonance. If the progressive dissonance gets assigned to a vanilla dissonance location  the game get's hanged up and you start picking up infinite amounts of dissonance (accompanied by the item pick up sound x100). It essentially becomes a softlock and require a game reboot. Additionally, it makes the game unbeatable. It's happened twice with the right chest after being Aten-Ra and the chest after shutting down Typhon. Here's the seed with my settings, where the dissonance randomizes to the typhon chest. If you need anymore info let me know, thanks!

[Seed.zip](https://github.com/Coookie93/LaMulana2Randomizer/files/8308551/Seed.zip)

**Comment by SoulSoldier64** [comment]
In hindsight, here's a text file of the spoiler log instead of the zipped seed folder.
[SpoilerLogTextFile.txt](https://github.com/Coookie93/LaMulana2Randomizer/files/8309865/SpoilerLogTextFile.txt)
!

**Comment by SoulSoldier64** [comment]
Update, it seems that it happens for progressive items in general. Had another seed where the Typhon dissonance randomized to research papers and the same thing happened. seed: -365026413

**Comment by lurch9229** [comment]
Can confirm this. Vritra dissonance chest and Aten-Ra for me

**Comment by Coookie93** [comment]
Fixed
