### ISSUE TITLE
Dissonance bug

### ISSUE THREAD

**Issue by lurch9229** [Coookie93/LaMulana2Randomizer#29]
if you buy 2 progressive beherits from a shop at one time the counter does not update properly. can lead to issues if all 6 dissonance are required

**Comment by Chrouya** [comment]
Here's some video footage of the issue:

When buying 2 dissonance from the same store individually (exit and re-enter, tracker shows +2)
https://clips.twitch.tv/SourNurturingChamoisAsianGlow-jhyELR99mA3jkTQe

When buying 2 dissonance from the same store at the same time (tracker only shows +1)
https://clips.twitch.tv/EntertainingSpicyEmuJebaited-pZDcTsilaD8d1Zkw

(in regards to the all 6 dissonance required, this was my misunderstanding of the setting "Guardians required" set to 5, making me believe I also needed only 5 dissonance, but ultimately I was only able to get 5 out of 6 dissonance in this run making it incompletable regardless)

**Comment by Coookie93** [comment]
Will look into this

**Comment by Coookie93** [comment]
Fixed
