### ISSUE TITLE
Hresvelgr doesn't spawn

### ISSUE THREAD

**Issue by Yuranaah** [Coookie93/LaMulana2Randomizer#30]
Hey, first of all great job on the randomizer. I'm having a ton of fun with all the different settings
Lately I've been encountering an issue with Hresvelgr not spawning at all making my run just end since I can't get to Hel.
I was wondering if there are additional spawn requirements I do not know about besides sealing Ratatoskr or is that an issue with the randomizer/seed?

Video for reference:
https://www.youtube.com/watch?v=cyD27u5hnAY

**Comment by Coookie93** [comment]
Have to kill Nidhogg too.
