### ISSUE TITLE
Item placement issue

### ISSUE THREAD

**Issue by Pannumato** [Coookie93/LaMulana2Randomizer#32]
My seed has Mother mantra on Secret treasure of life, can't remember for certain but I believe I need to chant mother and child at spiral boat to obtain SToL from Altar. Wiki doesn't clarify how to get from accessing the 9 soul gate to dropping the boat and starting the altar sequence.

**Comment by Coookie93** [comment]
Sorry for the 6month late reply, probably not need now but you can reach the Secret Treasure of Life by sealing the Corridor of Blood, then killing Heimdall.
